### ISSUE TITLE
[F] feat : 로그아웃시 알림 구독 제거 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#118]
안녕하세요 규현님!!

혹시 로그아웃시 해당 디바이스의 알림 구독이 제거되도록 설계가 되어있는지 궁급합니다!!
만약 되어 있지 않다면 나중에 알림 클릭시 액션에서 버그가 발생할 위험이 있다고 생각이 듭니다!!

## 🐌 Summary
로그아웃시 알림 구독 취소 반영

## 📝 To Do List
- [x]  로그아웃시 알림 구독 취소

**Comment by Arkady1356** [comment]
1. 알림 
-> Notification 모두를 지칭합니다
ex) 공지사항이 작성되었어요!, 콕 찔렀어요!, 댓글이 작성되었어요!, 새로운 회차가 등록되었어요! 등등 ...

2. 액션 
-> 알림을 클릭했을때 특정 화면을 보여주게 될 것이라고 생각합니다
ex) 공지사항 게시물 페이지 조회, 해당 스터디 조회, 회차 상세 조회 등등

3. 버그
이때 로그아웃 되었기 때문에 로그인 정보 및 Token이 없는 상태라 
각 페이지에서 '인증되지 않은 사용자'가 발생할 것이라 생각합니다!! 
(그 이외에도 잠재적 버그 가능성이 있다고 생각합니다 ex) 참여하지 않는 스터디에 대한 조회라던가 ... 혹시 모름)
(다른 사용자의 아이디로 로그인 했을 경우도 발생 가능하다고 생각)

=>
이러한 이유와 직관적으로 로그아웃시 알림이 안오는 것이 맞다고 생각했습니다!!
혹시 cost가 크거나 복잡하다면 
위에서 언급한 문제들을 다른 방법으로 해결 할 수 있도록 이야기 나누면 좋을 것 같아요!

**Comment by rbgus2002** [comment]
로그아웃 시 토큰 삭제하도록 구현해놓겠습니다! 이 부분은 작업할 게 많은 부분이라 뒤로 좀 미뤄놓았었습니다! 조만간 바로 구현해놓겠습니다~!

위와 별개로, 말씀하신 버그 부분은 당연히 예외처리 해놓아야 하는 부분입니다! 인증되지 않은 사용자인 경우(statusCode 401)면 로그인 화면으로 돌리도록 구현해주셔야 합니다..! 또한 나중에 말씀 드리려 했는데 JWT 만료 시에도 로그아웃 되도록 구현이 되어야 할 거 같습니다!

**Comment by rbgus2002** [comment]
JWT 만료시간 같은 경우는 server에서 정하는 것이므로 만료기간을 짧게 줄이고 함께 테스트 해보면 좋을 거 같습니다 (나중에 ㅎㅎ)

**Comment by Arkady1356** [comment]
넵넵 !! 확실히 토큰 만료 로그아웃도 고려해야겠네요... (나중에 ㅎㅎ)
