### ISSUE TITLE
[B] feat : 과제 콕찌르기 API 인자 추가 및 data 반영

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#140]
## 🐌 Summary
1. 과제 콕찌르기 API를 호출할 때 roundId를 함께 보내주세요 <br><br>
2. 과제 콕찌르기, 스터디원 콕찌르기, 과제 수행 알림 전송 시 data를 포함해서 넘기도록 했습니다.
flutter에서 data 받는 방법은 아마 [이 부분](https://firebase.google.com/docs/cloud-messaging/flutter/receive?hl=ko#handling_interaction)일 거 같습니다 참고해주세요
> 과제 콕찌르기 => key : "roundId"
스터디원 콕찌르기 => key : "studyId"
과제 수행 => key : "roundId"

## 📝 To Do List
- [ ]  반영

**Comment by Arkady1356** [comment]
과제 상세 조회페이지로 이동을 위해
추가로 studyId와 roundSeq(: 회차 순번)이 필요합니다.

따라서
{ 과제 콕찌르기, 과제 수행 }에 각각 studyId, roundSeq를 포함시켜주세요!!

**Comment by Arkady1356** [comment]
메세지를 읽었을때 해야할 일의 구분이 필요하다고 생각되었습니다.
이를 'type'으로 구분하고자 합니다.

'type'은 최종적으로 조회할 페이지로 나타냅니다.

ex) 스터디 조회: 'study', 회차 조회: 'round'
>'과제 콕찌르기' & '과제 수행': 알림 클릭시 해당 회차 조회 => 'type' == 'round'
>'스터디원 콕찌르기': 알림 클릭시 해당 스터디 조회 => 'type' == 'study'
>(예정)'공지사항 작성' & '댓글 작성': 알림 클릭시 해당 공지사항 조회 => 'type' == 'notice'

각 'type'에 따라 필요로 하는 추가적인 인자들이 있을 것입니다. (roundId, studyId, ...)

현재 플라이 테스트에 올릴 예정인 코드는 다음과 같습니다.
참조 바랍니다! 

``` dart
  void _handleMessage(RemoteMessage message) {
    switch (message.data['type']) {
      case 'study':
        int studyId = message.data['studyId'];

        _viewStudy(studyId);
        break;

      case 'round':
        int studyId = message.data['studyId'];
        int roundId = message.data['roundId'];
        int roundSeq = message.data['roundSeq'];

        _viewRound(studyId, roundId, roundSeq);
        break;

      // [Fallthrough] : not implemented yet
      case 'notice':
      case 'others':
      default:
        // TODO: implement later
        break;
    }
  }

```

**Comment by rbgus2002** [comment]
> 메세지를 읽었을때 해야할 일의 구분이 필요하다고 생각되었습니다. 이를 'type'으로 구분하고자 합니다.
> 
> 'type'은 최종적으로 조회할 페이지로 나타냅니다.
> 
> ex) 스터디 조회: 'study', 회차 조회: 'round'
> 
> > '과제 콕찌르기' & '과제 수행': 알림 클릭시 해당 회차 조회 => 'type' == 'round'
> > '스터디원 콕찌르기': 알림 클릭시 해당 스터디 조회 => 'type' == 'study'
> > (예정)'공지사항 작성' & '댓글 작성': 알림 클릭시 해당 공지사항 조회 => 'type' == 'notice'
> 
> 각 'type'에 따라 필요로 하는 추가적인 인자들이 있을 것입니다. (roundId, studyId, ...)
> 
> 현재 플라이 테스트에 올릴 예정인 코드는 다음과 같습니다. 참조 바랍니다!
> 
> ```dart
>   void _handleMessage(RemoteMessage message) {
>     switch (message.data['type']) {
>       case 'study':
>         int studyId = message.data['studyId'];
> 
>         _viewStudy(studyId);
>         break;
> 
>       case 'round':
>         int studyId = message.data['studyId'];
>         int roundId = message.data['roundId'];
>         int roundSeq = message.data['roundSeq'];
> 
>         _viewRound(studyId, roundId, roundSeq);
>         break;
> 
>       // [Fallthrough] : not implemented yet
>       case 'notice':
>       case 'others':
>       default:
>         // TODO: implement later
>         break;
>     }
>   }
> ```

제가 type을 key로 하도록 data를 추가하면 되는 것이지요? 알겠습니다~

**Comment by rbgus2002** [comment]
여러 개의 data를 추가해야하기 때문에 다음과 같은 Map을 putData해줍니다.
```java
Map<String, String> data = Map.of("type", "round", "studyId", studyId.toString(), "roundId", roundId.toString(), "roundSeq", "0");
```
현재 반영해서 배포했는데 과제 콕찌르기가 작동안되는 거 같아 확인 부탁드립니다.
