### ISSUE TITLE
[F] info : 빌드 분리 및 탈퇴하기

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#162]
### 1. 빌드 분리
테스트플라이트로 안하고 기존에 하던 flavor이용해서 했습니다.
prod, dev로 나누었습니다.

  패키지 명
  prod: com.ssu.groupstudy
  dev : com.ssu.groupstudy.dev

안드로이드와 Xcode에 prod, dev로 설정하여 빌드 하시면 됩니다. (사진 참조)
만약 없다면... 직접 설정을 만드셔야 하는데... ㅎㅎ 제발 있기를 ..!!

앞으로 저는
prod: '뜨끔'
dev: '뜨끔 개발'
이라고 부를 예정입니다.

*Info
카카오 공유
하나의 프로젝트에서 여러개의 패키지를 가지도록 설정하는 것이 별도로 신청하고, 복잡한 과정이기 때문에 이것은 포기했습니다.
=> 뜨끔 개발에서 공유해도, 카톡 클릭시 뜨끔으로 연결 됨

---

### 2. 탈퇴하기
탈퇴시
 1) "정말 계정을 삭제하시나요?"
 2) "삭제 시 모든 데이터를 다시는 복구할 수 없어요"

와 같이 두번의 다이얼로그를 거치도록 만들었습니다.

## 🐌 Summary
1. 빌드 다양화 적용
2. 탈퇴 API 적용 완

## 📝 To Do List
- [x] 확인 후 Close !

## 📷 스크린샷(선택)
<img width="400" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/759ba744-c337-4bc6-b2d9-fbd84409594d">

<img width="176" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/41054496-99bc-4fb2-bdf5-11fe6fecf428">

**Comment by rbgus2002** [comment]
오호 flavor 라는 게 있군요 알고 있겠습니다!
<br>
> 안드로이드와 Xcode에 prod, dev로 설정하여 빌드 하시면 됩니다. (사진 참조)
만약 없다면... 직접 설정을 만드셔야 하는데... ㅎㅎ 제발 있기를 ..!!

없네요.. ㅠㅠ 설정 세부 사항도 알려주시면 감사하겠습니다. 바쁘시면 당장은 괜찮을 거 같으니 천천히 해주셔도 좋아요!
해당 부분 확인해주시고 나서 issue close 하겠습니다
<br>
> 정말 계정을 삭제하시나요?

아니요 플래그로만 구분해서 논리적 삭제만 진행합니다~

**Comment by Arkady1356** [comment]
> 없네요.. ㅠㅠ 설정 세부 사항도 알려주시면 감사하겠습니다. 바쁘시면 당장은 괜찮을 거 같으니 천천히 해주셔도 좋아요!

하하.. 혹시 어디에서 없는건지 알려주시면 제가 나중에 하는법 이슈로 올리겠습니다

---

> > 정말 계정을 삭제하시나요?
> 
> 아니요 플래그로만 구분해서 논리적 삭제만 진행합니다~

앗...  엄.. 질문이 아니라 두 개의 문구를 보여주고 삭제된다고
적어둔것입니다 ㅋ.ㅋ.ㅋ..ㅋㅋㅋ

**Comment by rbgus2002** [comment]
1. xcode에서는 이 부분에서 확인하면 되는 건가 싶습니다. dev만 있네요
![image](https://github.com/rbgus2002/studygroup/assets/62997391/648b8a80-4229-4fcd-b409-14910c04d668)


2. 안드는 따로 configurations을 만드신건가요? 아예 저는 main.dart 밖에 없습니다!

**Comment by Arkady1356** [comment]
1. 안드로이드 세팅

Edit Configurations ...  > 좌측 상단 +

Dart Entrypoint: {main과 동일}
Build Flavor: 각각에 맞추어 dev || prod

<img width="771" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/04a6a6d1-7ddd-43dd-98fb-b442a5551d7d">

---

2. Xcode 세팅

Manage Scheme > dev 선택 > ... > Duplicate

복사한 Shceme 이름을 prod로 설정
좌측에 { build, run ... }의 Build Configuration 세팅을 prod로 변경

<img width="335" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/eef10a23-a68a-499f-a499-72f89972031f">

<img width="275" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/154987c9-0cb3-4f34-9da8-c169ab341269">

<img width="874" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/6002937a-f815-4a0e-97de-3a845a293895">

<img width="800" alt="image" src="https://github.com/rbgus2002/studygroup/assets/86937581/9b56beb0-e787-4463-97d8-370b30fe1aa7">
