### ISSUE TITLE
불필요한 API 호출 수정 요청 (카카오톡 초대 공유)

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#171]
## 🐌 Summary
현재 멤버 추가하기 FLOW에서 불필요한 API 호출이 일어나 수정 요청 드립니다. 요청한 흐름은 다음과 같습니다.

1. 홈화면에서 스터디 상세 페이지로 진입합니다.
<img width="1512" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/911d965b-6d91-4713-a098-a7a14ff81aaf">
<br><br>
2. 멤버 추가 버튼을 클릭합니다.
<img width="1512" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/2377fab7-ed94-4d27-bc5c-380905cb234a">
<br><br>
3. 초대코드 공유 (카카오톡)를 클릭한 뒤 자동으로 카카오톡 앱으로 리다이렉트 됩니다. 이 때 스터디 상세페이지 진입 시에 호출하는 API들이 모두 호출되는 거 같아요
<img width="1512" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/4e79e016-cf82-4a08-b5cc-c67adcb2d959">
<br><br>
4. 카카오톡 공유를 끝내고 다시 앱으로 진입하는 경우 또 한번 위처럼 불필요한 API들이 호출됩니다.
<img width="1512" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/9a516926-9976-4aa8-adfd-be4e548f8d82">
<br><br>
5. 뒤로가기를 눌러서 스터디 상세페이지로 돌아옵니다.
<img width="1507" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/76045ca2-a1a9-4f76-8ef2-d21a7b69bdbb">

<br><br><br>

제 생각에는 멤버 추가 시에, 스터디 상세페이지를 위한 API 호출들이 필요없다고 생각합니다. 따라서 이 경우에 2번의 경우만 초대코드 가져오는 API 호출하도록 하면 좋을 거 같습니다

## 📝 To Do List
- [ ]  불필요한 API 호출 방지

**Comment by Arkady1356** [comment]
우선 문제 발생이 
1. 앱이 백그라운드로 전환될때
2. 다시 포그라운드로 전환될때 
 
다음과 같은 현상이 발생함을 확인하였습니다..!

해당 문제는 바로 해결하기엔 좀 시간이 걸릴 것 같으니
다른 Issue들을 우선적으로 해결하고 차후 수정하도록 하겠습니다 !!

**Comment by rbgus2002** [comment]
이 부분은 스터디 초대코드에 유효시간 주면 FLOW, UI가 바뀔건데 그 때 다시 한번 확인해보죠
