### ISSUE TITLE
[B/F] bugfix : 토큰 재등록 관련 notification 버그 수정 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#173]
## 🐌 Summary
현재 앱 제거 후 다운로드 받거나, 앱을 업데이트 하거나 등 FCM token이 변경되는 경우 알림이 더이상 안오는 이슈가 존재합니다. 해당 이슈가 발생하는 이유는 다음과 같아요
1. 변경되기 전 token이 subscribe하고있는 topic들이 존재 (스터디 및 공지사항)
2. token이 재발급되는 경우 해당 topic들을 다시 subscribe 해주어야 함
3. 현재 해당 로직이 없음.
4. 앱 제거 후 다운로드 받거나, 앱을 업데이트 하는 경우 앱 내에서 로그인이 계속 유지됨

**<해당 이슈가 발생하지 않도록 하려면??>**
[BE] => 로그인 하는 경우 토큰을 등록하고 (현재와 같은 방식) 새롭게 토큰이 등록되는 경우면 속해있는 모든 스터디를 다시 topic subscribe 해주는 로직 추가
[FE] => 위 4번의 경우 재 로그인을 하도록 함
**위 방식으로 가는게 제일 좋을 거 같아요.** 
(그러진 않을 거 같지만 혹시나 정 불가능한 경우 홈화면 새로고침 하는 경우에 매번 검사를 하는 방법도 있습니다! 공식문서에 따르면 권장사항이 아니긴 해요)

앱 홍보 전인 안드로이드 앱이 출시되기까지 꼭 해결됐으면 하는 문제에요 감사합니다~!

## 📝 To Do List
- [x] FE 요청 사항 반영 (JW)
- [x] BE 요청사항 반영 (GH)

**Comment by rbgus2002** [comment]
> [BE] => 로그인 하는 경우 토큰을 등록하고 (현재와 같은 방식) 새롭게 토큰이 등록되는 경우면 속해있는 모든 스터디를 다시 topic subscribe 해주는 로직 추가

로직 추가하여 개발 서버에서 테스트 하고 운영서버에 반영 해놓았습니다

**Comment by Arkady1356** [comment]
> [FE] => 위 4번의 경우 재 로그인을 하도록 함

1.0.3+4부터 적용될 예정입니다 ~
