### ISSUE TITLE
[F] feat : 기본 스터디 컬러 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#175]
안녕하세욥 규현님

오늘 친구들에게 앱 전파하던 도중에
스터디 기본 색상이 연한 녹색 임을 확인하였습니다..!

스터디를 최초 생성할때 열심히 고민해서 골랐는데,
스터디원들에게는 보여지지 않아서 아쉽습니다...
(한편 연한 녹색 + 다크 모드 = 버그인 것 아니냐고(투명해졌다고) 오해받았었습니다 ㅋㅋ)

이러한 이유로
방장이 최초에 선택한 색상으로
다른 사용자들에게도 기본으로 보여지는 것은 어떨까요? 

---
또한 스터디 컬러 선택이 부족하다는 유저의 의견도 있었습니다 !!
추후 더 많은 색상을 지원하는 것은 어떨까요? 

## 🐌 Summary
1. 스터디 기본 컬러를 스터디 생성시 설정한 색상으로 세팅
2. 추후 색상 다양화 고려 어떠신가욥

**Comment by rbgus2002** [comment]
1. 스터디 생성 시에 설정한 색상으로 세팅하는 것은 현재 설계 기준으로는 불가능합니다 ! 하지만 현재 방장이 사용 중인 색상을 기본 색상으로 지정하는 것은 가능한데, 해당 방식으로 수정할게요 !
2. 넵 저도 색상 더 추가하는 건 너무 좋습니다 ! 지금 존재하는 컬러칩들이 그닥 이쁘다는 생각도 안들어서 빠른 시일 내에 색상을 수정&추가 했으면 좋겠어요

**Comment by rbgus2002** [comment]
2번은 별도의 이슈로 분리했습니다. #178

**Comment by rbgus2002** [comment]
> 스터디 생성 시에 설정한 색상으로 세팅하는 것은 현재 설계 기준으로는 불가능합니다 ! 하지만 현재 방장이 사용 중인 색상을 기본 색상으로 지정하는 것은 가능한데, 해당 방식으로 수정할게요 !

수정해서 반영했습니다. close issue 할게요 ~
