### ISSUE TITLE
[B/F] feat : 스터디 색상 다양화 

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#178]
## 🐌 Summary
현재 스터디 색상은 24가지를 선택할 수 있습니다. 조금 더 다양하게 색상을 선택할 수 있도록, 스터디 색상 추가가 필요합니다 !

## 📝 To Do List
- [ ] 추가할 색상 논의
- [ ] 현재 색상에서 제외할 부분 선택하기

## 📷 스크린샷(선택)
<img width="306" alt="image" src="https://github.com/rbgus2002/studygroup/assets/62997391/170b06d8-33de-41e0-9806-9ed902570ea8">

**Comment by rbgus2002** [comment]
회사에서 그램 받았어??!

---

개인적으로 선택 가능한 색상 개수 자체를 늘리는 걸 제안해요. 
직접 색상 선택할 수 있으려면 기본 color picker 안예뻐서 또 디자인도 해야할 뿐더러, 사용자가 직접 선택한다고 얻는 메리트가 없을 거 같아요 (오히려 직접 고르면 안예쁠 듯)

---

todo mate를 레퍼런스로 삼아서 동일하게 갈까요?
![IMG_9281](https://github.com/rbgus2002/studygroup/assets/62997391/0f543397-2d9e-4619-a973-c252d561923b)
![IMG_9282](https://github.com/rbgus2002/studygroup/assets/62997391/b75dd992-cd4c-4971-ac31-84f4f6167c2a)

**Comment by Arkady1356** [comment]
오히려 많기만하면 더 부담스럽지 않아??
나 방금도 Todo-mate 색상 오랜만에 바꿨는데
뭔가 딱 원하는 색은 막상 없고, 필요없는 색만 많은 느낌이라 ..

---

우리 사용자들은 주로 무슨색 고르는지 통계 정보도 알려주면 좋을 듯!

---

다른 앱에서는 색상 선택 자유도가 어떤지도 궁금하다

---

채령님한테 아이디어를 듣는건.. 불가능하나?

**Comment by rbgus2002** [comment]
헉 나는 직접 고르는 게 훨씬 더 별로고 색 다양하고 예쁜 거 많아서 좋다 생각했음 ... ! 음 커스텀 할 수 있는 컬러 피커 디자인은 어떻게 되는 거지 그럼?

> 우리 사용자들은 주로 무슨색 고르는지 통계 정보도 알려주면 좋을 듯!

이거는 진자 좋다 이건 기능 구현해서 뭐 BEST! 요렇게 달아줘도 좋을 듯?

**Comment by Arkady1356** [comment]
> 이거는 진자 좋다 이건 기능 구현해서 뭐 BEST! 요렇게 달아줘도 좋을 듯?

오 좋다!!

흐음... 한번 Color Picker Design Refference를 찾아봤는데 이쁠 수가 없긴 하다 ㅋㅋㅋ

그러면 
1. 지금의 UI를 유지하고
2. 좌우로 스와이프로 넘기는 식으로
3. 여러 페이지(3 페이지 정도)로 색상들을 보여주는 것

은 어떰?
한번에 너무 많이 보여주면 부담스러우니까 분산

들어갈 색상들 리스트는 어떻게 선정할까...
채령님한테 조언 못받겠지...

**Comment by rbgus2002** [comment]
추후 **디자이너 섭외 후에** 디자인 전면 개선 건으로 해당 태스크 관리할게요
