### ISSUE TITLE
[F] feat : 순서 변경 구현 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#180]
## 🐌 Summary
1. 이제 슬슬 스터디, 과제에 대해 순서를 변경할 수 있도록 구현하면 어떨까요? 구현 방법은 생각해놨어요 (feat. 다양한 ~ 랭킹 알고리즘)
2. 1번을 구현하면서 회차의 순서 개념도 변경했으면 좋겠어용. 약속 시간에 상관없이 stack처럼 위에 쌓이고 사용자가 직접 회차를 변경하는 방식으로욤. 어떤 회차를 홈화면에서 보여줄지는 기획적으로 좀 더 생각해봐야겠지만요 !

## 📝 To Do List
- [ ] 스터디, 과제 순서 변경할 수 있도록 구현
- [x] 회차 순서 개념 변경 논의

**Comment by Arkady1356** [comment]
오호 랭킹 알고리즘은 뭘지 궁금하네요

하지만 회차 순서 변경은 반대합니다!! 
히스토리가 쌓이는거지 거기서 순서바꿀 수 있는건 직관적이지 못하고 너무 부수적인 느낌이에요

스터디 및 과제 순서 관련 해서는 알고리즘을 함 들어보고 적용까지 얼마나 걸릴지 가늠해보겠습니다!

**Comment by rbgus2002** [comment]
> 스터디 및 과제 순서 관련 해서는 알고리즘을 함 들어보고 적용까지 얼마나 걸릴지 가늠해보겠습니다!

제가 알고리즘을 설명해드리는 건 아니고 그냥 다양한 알고리즘이 있다 이정도로 말씀 드리려고 적어놨어요. 제가 프론트 단에서 수정해야하는 부분은 따로 요청 드리겠습니다

**Comment by Arkady1356** [comment]
> API 요청 시에 수정해야하는 부분 말고 앱 단에서 꾸욱 눌러서 변경하는 그런 동작은 따로 구현 부탁드립니다~

넵 적용해보겠습니다
다만 조금 시간은 걸릴 수 있을 것 같아요~ 
다른 쉬운 업무 먼저 해결하고 해보겠습니다!

**Comment by rbgus2002** [comment]
앞으로 논의사항이 있으면 Discussions 활용해보면 어떨까요?
