### ISSUE TITLE
[F] feat : 공지사항 무한스크롤 적용

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#181]
## 🐌 Summary
1. 공지사항이랑 회차 이제 슬슬 무한스크롤 적용할까요
2. 회차는 적용하려면 #180 에서 말씀드렸지만 회차에 순서 개념을 추가해야함요
3. 그리고 해당 이슈랑은 다른 얘기인데 스터디 생성 개수 5개 제한한 거처럼 회차도 n개로 제한을 두는 건 어때요? 뭐 프리미엄 명목으로 돈 뜯을라고 그러는 게 아니라 느림 이슈 발생할까봐? (3-40개 정도로 넉넉하게 두면 좋을 듯 함)

## 📝 To Do List
- [ ] 1
- [ ] 2
- [x] 3

## 📷 스크린샷(선택)
졸리다

**Comment by Arkady1356** [comment]
1. 함 try 해보죠
2. 회차 순서 에바 띠용
3. 넵넵 좋은것 같습니다!!

**Comment by rbgus2002** [comment]
1. 무한스크롤이 좋을 거 같은데 관련해서 프론트 쪽에서도 어떻게 작업하는지 확인해주세요

3. 30개로 할게요~

**Comment by Arkady1356** [comment]
엄 다시 생각해보니
round 30는 너무 적을 것 같아요..!

일주일에 한번씩 30회 하면 210일이라 1년을 못채우는 점이 걸립니다..!
60회는 어떠신가요?
