### ISSUE TITLE
[F] feat : 공지사항 알림 on/off 기능 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#182]
## 🐌 Summary
해당 기능 구현하려면 FCM 알림과 별도로 저희 DB에 테이블 만들어야 함요
시간 측면에서 꽤 코스트가 있는 작업인데, 중요한 기능이라고 생각이 드시는지요?
중요한 기능이라고 생각들면 구현함요

## 📝 To Do List
- [ ]  공지사항 알림 on/off 기능

**Comment by Arkady1356** [comment]
시간 측면이라 하면

1. 개발 시간
2. 서버에서의 작동 시간

??

1.이라면 차후 하고플때 해도 나쁘지 않은 것 같습니다

**Comment by rbgus2002** [comment]
넹 1이었어요 Later 달아둘게여

**Comment by rbgus2002** [comment]
공지사항 기능 사용이 저조하여 해당 이슈는 일단 close 하겠습니다
