### ISSUE TITLE
[F] feat : 추후 작업 계획 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#183]
## 🐌 Summary
재우님 요즘 회사 다니고 적응하느라 바쁘신가요??
저희 뜨끔 계속 업데이트 하면서 운영하려면 조금은 더 시간 투자하는 게 좋을 거 같아요. 돈 빠져나가는 거 보면 노력을 안할 수가 없습니다.. ㅎㅎ

아예 때려치는 건 아니고 계속 하실 거라고는 말씀 하셨으니 다음을 논의해보고 싶어요
1. 일주일에 얼마의 시간을 투자할 수 있는 지
2. 지금은 저희 프로젝트 태스크 관리가 전혀 안되고 있는데, 태스크 관리 뿐 아니라 플젝 추후 진행 관련해서 논의할 사항 있으면 여기서 빠르게 결정하고  완전히 재정비하고 싶어요

바쁘신 건 압니다 ~~ 자유롭게 의견 주세요. 
사실 제 의견은 더 시간 투자해서 꾸준하게 신기능 업데이트도 하고 으쌰으쌰 하고싶습니다. 사용자 늘고 실제로 쓰고 있는 사람들 보니까 재밌어서 더 흥미가 생기네요 !

## 📝 To Do List
- [ ]

**Comment by Arkady1356** [comment]
음 일단 우리 파트가 좀 최전선이라
기본 20시 퇴근, 주말 출근이 만연한 분위기 이기는 합니다..ㅎㅎㅎ

저는 아직 신입이라 괜춘하긴한데,
음 일단 이번주 주말까지는 주말마다 계속 약속이 있어서 서울로 올라갔지만,
이제 다음주 주말부터는 좀 안올라가고 쉬려고 생각 중입니다!!

대략 12시간 ~ 정도 투자할 수 있지 않을까요??
