### ISSUE TITLE
[F] feat : 무한 할일 체크 방지 

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#184]
친구가 눈앞에서
무한 알림 생성!! 이러면서 체크 박스 광클하는거 보고 충격받음
근데 그거 내용이 실제 그날 회의에서 나왔다는 거 듣고 2차 충격

## 🐌 Summary
찌르기와 같이 할일 체크 업데이트에 지연을 추가

## 📝 To Do List
- [x]  할일 체크 Lazy Update

**Comment by rbgus2002** [comment]
> 근데 그거 내용이 실제 그날 회의에서 나왔다는 거 듣고 2차 충격

무슨 회의여???

**Comment by Arkady1356** [comment]
ㅋㅋㅋㅋㅋ 
회사 다른 파트 업무 회의에서 
버튼 광클하는거에 대응 되어있냐고 물어보면서 광클했었대

그거 생각나서 우리 앱에서도 체크 버튼 광클해봤다나 ㅋㅋ
