### ISSUE TITLE
[F] feat : 회차 날짜 변경 시 회차 재정렬 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#186]
## 🐌 Summary
1. 스터디 상세 페이지 진입
2. 특정 회차 날짜 변경
3. 회차 리스트 불러오는 API 호출해서 회차 리스트 재정렬

위 사항 반영해주세요 ~

## 📝 To Do List
- [ ]  회차 순서 변경 시에 API 호출을 통한 순서 즉시 반영

**Comment by Arkady1356** [comment]
구지 refresh 를 해줘야 할까요?
불필요한 Cost가 아닌지 의문이 듭니다!!

pull to refresh도 지원하기 떄문에
사용자가 필요하면 알아서 refresh 하지 않을까욥!?!?

**Comment by rbgus2002** [comment]
다른 부분들도 마찬가지로 생각했기 때문에 요청 드렸었고 (홈화면 진입 시 변경 사항 반영), 날짜를 변경했는데 정렬이 안되어 직접 pull to refresh를 해야만 반영되는게 매우 어색합니다 ! 
cost야 더 들겠지만 큰 문제가 아니라고 생각해서 당장은 refresh가 되었으면 좋겠고, 추후에 해당 cost 때문에 문제 생기면 그 때 대응해보죠~~

**Comment by Arkady1356** [comment]
놉!! 저는 여전히 반대인게,
날짜를 하나를 수정하다가 잘못 수정하면 
리프레쉬되면서 저 멀리로 사라지면 따로 찾아서 수정해야하고 ...
번거로움이 있지 않을까요?

리프레쉬 될때 모션도 애니메이션 같은게 있는게 아니라 매우 부자연스러울 것 같아요...
약간 비유하자면

개 구린 정부 사이트같은 곳에서 
뭐 한칸 입력할때마다 리프레쉬 되면서 화면 깜빡거리는 그런 갬성...

그럼~에도 ~ 불~구 하고 라면!!
바로 반영하겠습니다 ㅎㅎ

**Comment by rbgus2002** [comment]
이 부분은 상충되는 의견이니까 다른 앱들 참고해보면서 조금 더 얘기해보시죠 레퍼런스 가져와서 말씀해주셔도 좋을 듯요

**Comment by Arkady1356** [comment]
오... 방금 구현해봤는데

Date Picker가 화면을 가리고 있어서
Refresh 하는 모습을 안보여주고
=> 엄청 SMOOTH하게 바뀌네 ㅋㅋㅋ

Date Picker가 가리고 있을거라고는 전혀 상상치도 못했다...
바로 해당 내용 적용 스키겠습니다!! (내일)

**Comment by rbgus2002** [comment]
고생 많으십니다 ~!
