### ISSUE TITLE
[F] feat : BE, FE git repository 분리 및 비공개 변경

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#187]
## 🐌 Summary
BE와 FE의 repository를 분리하는 게 좋을 거 같습니다. main에 flutter 코드가 merge 되는 경우 rebase 할 때 ci/cd 관련 이슈가 있어서 그렇습니다~
BE 쪽에서 ci/cd 적용 및 기타 secret 설정들이 많이 되어 있어서 FE 쪽 코드를 재우님 개인 레포에 따로 옮겨주실 수 있나요?

## 📝 To Do List
- [ ] FE 코드 분리해서 개인 repo로 이관
- [ ] 이관한 repo를 private으로 변경

**Comment by Arkady1356** [comment]
repo분리시 main에는 어떤식으로 반영하나요?
다른 repo 사이에서 PR이 가능한가요?

**Comment by rbgus2002** [comment]
1. 현재 레포에 있는 FE/* 코드는 모두 지워야 할 것 같습니다.
2. 넵 이후에 다음 버전 브랜치 만들 때 천천히 반영해주시면 감사하겠습니다.

---

> repo분리시 main에는 어떤식으로 반영하나요?

어차피 개발서버 및 운영서버와 HTTP 통신하니까 굳이 같은 repo에 있을 필요가 없는 거 같아서 해당 issue 만들었습니다. 오히려 rebase도 해야하고 여간 불편한게 아닙니다 ㅎㅎ.. 대부분 BE, FE 나눠서 작업하더라구용. 
(main에는 지금과 같은 branch 전략으로 repo 나누셔서 작업해주시면 됩니다.)

> 다른 repo 사이에서 PR이 가능한가요?

다른 repo 사이에 PR은 안되는 걸로 알고 있어서 issue 관리를 특정 하나의 repo 에서 하거나 github 말고 대안을 찾아보는 게 좋을 거 같아요

**Comment by Arkady1356** [comment]
아하 그러면 별도의 repo, 별도의 main branch .. 로 생각하면 되는거죠?
넵넵넵

**Comment by rbgus2002** [comment]
아직 작업 안하신거면 추후로 미뤄도 좋을 거 같습니다~ 나중에 다시 이야기 할게욥
