### ISSUE TITLE
[] feat : 정기적으로 전체 알림 전송 문구 논의

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#191]
## 🐌 Summary
특별히 주기를 정해놓지는 않되, 가끔씩 생각날 때 firebase console 가서 전체 알림 줘도 됩니까?
음 뭐 리뷰 부탁한다, 할 말 있으면 문의하기 기능을 활용해라 등의 말? 이러한 문구는 레퍼런스를 좀 찾아봐야겠습니다.
문구 추천도 받습니다~ 뉘앙스만이라도 ㅎㅎ

## 📝 To Do List
- [x]  전체 알림 줘도 되나 허락 구하기~

**Comment by Arkady1356** [comment]
오호 나쁘진 않은 것 같습니다만

---
제 주변 사용자들이 알림이 너무 많은 느낌이라고 합니다
=>
1. 알림 최적화 필요(문구 최적화, 가능하다면 알림 압축 (그룹화?))
2. 전체 알림을 난발하지 않고 조심스럽게 할 필요성 유

**Comment by rbgus2002** [comment]
1. 문구 최적화는 문구 글자 수를 줄이자는 말일까요?? 그룹화 부분 이해가 잘 안돼서 자세히 설명해주시면 ㄱㅅㄱㅅ
2. 그렇네융 좀 더 생각해볼게여

**Comment by Arkady1356** [comment]
1. 문구 최적화
  : 적은 내용으로 1) 가독성을 높이고, 2) 피로감이 적게하고, 3) 다른 알림간 구분이 쉽게 가능하도록
  현재에는 너무 길게 적혀지는 느낌도 있고,
  공지사항, 찌르기, 댓글 등의 알림이 쉽게 구분되지 않는 것 같아요.
  추가로 누가 수행했는지도 직관적으로 알수 없는점이 아쉬워요

2. 알림 그룹화 [DEPRECATED]
  현재에는 
  "1알림-1박스" 형태잖아요?
  => 알림이 많아지면 너무 박스가 많아져서 스크롤이 길어지는 문제가 발생합니다!!
  
  그렇기 때문에 과제 수행을 예시로 들면
  같은 사람이 수행한 여러개의 과제를 하나의 박스에서 콤팩트하게 표현할 필요가 있다고 생각합니다!!
  
  이었는데... 이런게 없네 찾아보니까
  뭔가 경험해본적 있는 것 같은 기분인데 뭐지 ...ㅋㅋㅋ

  이거는 없던 걸로,,,ㅋㅋㅋ

**Comment by rbgus2002** [comment]
> 1. 문구 최적화

저도 공감합니다 싹 정리해서 알림 메세지 더 깔끔하게 변경하고싶어요..!

**Comment by rbgus2002** [comment]
+ 이건 다른 얘기지만 그냥 개발 서버 없앨까요? 뜨끔에 많이 손가는 부분도 없어서 굳이 개발서버 있을 필요성이 잘 안느껴집니다..!

**Comment by Arkady1356** [comment]
넵 개발 서버 제거에 동의합니다~ 대신 제거시 이슈로 알려주세요!
