### ISSUE TITLE
[F] feat : 사용자 활동 날짜 갱신 API 연동 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#193]
## 🐌 Summary
`PATCH /api/users/activate-date` 사용자의 activateDate를 갱신하는 API를 구현했습니다.
현재는 해당 field가 정상 동작하지 않고, 기존의 홈 화면 불러오는 API에서 활용할 수 있는 부분이 없다고 판단해 API를 분리했습니다.
홈화면 갱신하는 경우에 해당 API를 호출시켜 주시면 됩니다 ~ 미리 운영계에 배포해놓겠습니다.

## 📝 To Do List
- [ ] 홈화면을 구성하는 API들 호출 시에 함께 해당 API 호출하도록 연동

**Comment by Arkady1356** [comment]
version 1.0.4+5 부터 반영될 예정입니다 =)
