### ISSUE TITLE
[FE] 공지사항 생성 시간 에러 수정 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#230]
## 🐌 Summary
`2024-06-13 14:38:59.067296`에 생성된 공지사항이 어제로 표기되는 문제가 존재해요. 아마 하루 이상이 지난 공지사항이 모두 어제로 표기되는 것 갗습니다.
FE 쪽에서 코드 오류로 보이는데 한번 확인해보시고 버그 수정 부탁드립니다!

## 📝 To Do List
- [x]  공지사항 생성시간 표기 오류 수정

## 📷 스크린샷(선택)
<img src =https://github.com/rbgus2002/studygroup/assets/62997391/db4f3e88-ce09-4231-b9c9-d5478e48241a width=250 >

**Comment by Arkady1356** [comment]
### Trouble Shooting
---

* '어제'를 판단하는 조건이 (nowTime.day - dateTime.day < 2) 임을 확인
* DateTime의 day를 년도를 날짜로 변환했을때 (3226753일 요런 느낌)으로 생각하고 코드를 작성하였음
* 하지만 실제 DateTime의 day는 몇월 며칠에 해당하는 며칠을 표시함 (ex. 06.23 -> 23)
* 따라서 로직을 다음과 같은 형태로 개선해야함
* ((nowTime - dateTime).day < 2)

---

지금 교육 받는 중이라 맥북이 없어서 검증을 해볼 방법이 없네요 ㅎㅎㅎ
자료를 더 찾아보고 위의 Solution이 맞는지 분석해보고,
주말에 시간날때 반영하도록 하겠습니다 ㅎㅎ

**Comment by Arkady1356** [comment]
수정사항이 크지 않고, 예상 가능한 결과이기 때문에 테스트 없이 merge & close 하겠습니다 ..!!
