### ISSUE TITLE
[FE] 사용자 관련 API 3개 스펙 변경 요청

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#233]
## 🐌 Summary
아래 API들에 대해서 수정이 필요합니다. 아래 수정사항에서 변경 전 API는 그대로 두고 새롭게 API를 생성하였습니다. 변경 작업이 끝나고 추후에 API 삭제할 예정입니다.
자세한 스펙은 [스웨거](http://54.180.56.102:8080/swagger-ui/index.html#/)에서 확인 가능합니다.

### 사용자 프로필 편집 API
* 변경 전 : `PATCH /api/users`
* 변경 후 : `PATCH api/users/:userId?nickname={}&statusMessage={}`

### 사용자 탈퇴 API
* 변경 전 : `DELETE /api/users`
* 변경 후 : `DELETE api/users/{userId}`

### 사용자 활동시간 갱신 API
* 변경 전 : `PATCH /api/users/activate-date`
* 변경 후 : `PATCH api/users/{userId}/activate-date`

## 📝 To Do List
- [x]  사용자 프로필 편집 API
- [x] 사용자 탈퇴 API
- [x] 사용자 활동시간 갱신 API

**Comment by rbgus2002** [comment]
@Arkady1356  리마인드 드립니다~

**Comment by Arkady1356** [comment]
> 사용자 프로필 편집 API  

스웨그를 보면 userProfile이 변경되지 않는 경우에는 null을 넣어야만 한다고 기술하는데
이 부분을 위해서 아래와 같이 기이한 코드가 작성됩니다..!!

``` dart
   // #Case: profileImage is not null -> add MultipartFile
    if (profileImage != null) {
      request.files.add(await http.MultipartFile.fromPath('profileImage', profileImage.path));
    }
    // #Case: profileImage is null -> add data to null
    else {
      Map<String, dynamic> data = { "profileImage": null, };
      request.files.add(http.MultipartFile.fromString(
        'dto', jsonEncode(data), contentType: MediaType("application","json"),));
    }
```


혹시 이 부분이 필수적일까요? 아예 "userProfile"을 비운 상태로 보내면 문제가 발생할 까요?

**Comment by rbgus2002** [comment]
userProfile을 비운 상태로 보내면 자동으로 null 처리 되어 문제 없을 거 같습니다 ! 혹시나 테스트 해봤을 때 안되면 멘션 주세요~
(오해의 소지가 있게 swagger에 문서 작성해놨네요 ㅈㅅ__)

**Comment by rbgus2002** [comment]
FE 작업 내용이라 제목 수정했어요 ~
