### ISSUE TITLE
공통 할일 추가와 콕찌르기 기능 논의

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#43]
안녕하세요 규현님! 

이번에 '회차 상세보기'에서
공통 할일에 할일을 추가하면 다른 사용자들에게도 할일이 추가되도록 '보여지는' 기능을 추가하였습니다.

이때 아시면 좋을것 같은 내용들을 담아보았습니다.

---
### 1. 할일 그룹의 공유 여부 (공통 할일 여부)
<img width="338" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/86937581/756649b4-0ad7-4484-b020-7a2d684dcf80">

사진에 매핑되는
taskType과 task 리스트를 나타내는 TaskGroup 클래스가 있는데요,

기능 구현을 위해 해당 클래스에 bool isShared을 추가했습니다.
이는 공유되는 테스크타입인지를 나타냅니다 (GROUP은 하나의 예시)

``` dart
class TaskGroup {
  String taskType;
  List<Task> tasks;
  bool isShared;            //< this member is added
}
```

이는 나중에 혹시 모를 taskType추가에 대한 확장성을 고려하면서 생겨난 것인데요,
이때 현재에는 isShared는 다음과 같이 판별하는데요,

``` dart
static Set<String> sharedTaskGroups = { 'GROUP' }; // hard coding...

// set에 포함 여부
taskGroup.isShared = sharedTaskGroups.contains(taskType);
```

만약 서버에서도 할일 공유 여부를 저장하고 있다면
혹은 이후 taskType에 확장 자유도를 높이는 경우

isShared : 공유되는지 여부도 같이 서버에서 반환해주시면 감사하겠습니다!

대응 API : GET api/tasks

---
### 2. 가상의 할일과 새로운 콕찌르기의 모순
현재는 다른 사람에게 추가되는 것이 가상의 할일이기 때문에 
taskId = -1 (nonAllocatedTaskId) 를 가지는데

방금 만든 다른 사람의 할일도 찌를 수 있게 하려면
가상이 아닌 진짜 taskId들을 가지고 있어야 가능해집니다.
(체크박스를 통한 콕 찌르기 도입의 경우)

나중에 콕찌르기 기능이 확정되면 이야기를 나누면 좋을것 같아 적어둡니다!!

**Comment by rbgus2002** [comment]
선생님 셤 끝나면 열작업 부탁드립니다!! 스피드하게 끝내봅시다~!
