### ISSUE TITLE
[F] feat : 회원 가입 API 수정 요청

### ISSUE THREAD

**Issue by Arkady1356** [rbgus2002/studygroup#66]
회원 가입 API에서 프로필 이미지를 업로드 할 수 있도록 수정해주세요!

(현재) : URL 형식으로 업로드 -> 불가
(니즈) : Multipart 형식으로 파일 업로드 가능하도록 수정

꼼수로
회원 가입 API + 프로필 수정 API을 해보려 했는데
프로필 수정 API가 로그인 되어야 이용 가능하다는 한계가 있더군요...

## 🐌 Summary
회원 가입 API를 수정해주세요
- 프로필 이미지를 파일 형태로 업로드 할 수 있도록 해주세요

## 📝 To Do List
- [x] 회원 가입 API에 프로필 이미지 업로드 가능하도록 수정

**Comment by rbgus2002** [comment]
1. 기존 회원가입 dto 내에 picture 제거되었습니다.
2. 기존 회원가입 dto 내에 phoneModel이 제거되었습니다. 
3. 회원가입 시에 user의 phoneModel, statusMessage는 null값이 들어갑니다.
4. 회원가입 시에 프로필 이미지를 입력하지 않은 경우 picture은 null값이 들어갑니다.
5. body에 image가 추가되었습니다.
6. request body의 인자가 크게 'dto'와 'profileImage' 두가지 입니다. dto의 경우 반드시 contentType을 application/json으로 지정해주어야 합니다. 아래 사진 참고 (따라서 swagger에서 테스트가 불가능하여 postman으로 api 테스트 진행했습니다.)
<img width="1076" alt="image" src="https://github.com/rbgus2002/groupstudy/assets/62997391/528bbd5b-9bf2-4286-b0f7-414a782f285c">

7. profileImage는 사용자가 프로필 이미지를 업로드하지 않는 경우 body에서 제외하고 요청할 수 있습니다. (body에서 제외하고 요청하는 경우 null값입니다.)

확인하시고 궁금한 점 있으면 말씀해주세요!

**Comment by rbgus2002** [comment]
해당 부분 반영 완료 됐으면 issue close 부탁드립니다!

**Comment by Arkady1356** [comment]
반영은 하였으나 테스트를 할 방도가 없어 차후에 테스트가 필요합니다!

**Comment by rbgus2002** [comment]
> 반영은 하였으나 테스트를 할 방도가 없어 차후에 테스트가 필요합니다!

휴대폰 번호 중복 검사 때문에 테스트할 방도가 없다고 하신거면 db에서 기존의 아이디 휴대폰번호를 잠깐 수정하신 뒤에 테스트 하고 다시 돌려놓는 방법도 있습니다!!
