### ISSUE TITLE
[F] feat : 회차 삭제 이후 로딩에 관한 질문

### ISSUE THREAD

**Issue by rbgus2002** [rbgus2002/studygroup#97]
## 🐌 Summary
현재 회차를 삭제하면 스터디 상세페이지로 넘어가게 됩니다.
이 과정에서 사용자가 직접 새로고침을 해야 반영이 되는 것으로 확인했는데, 이 과정에서 회차 목록 불러오는 API를 호출하여 최신 정보로 반영을 시켜줘야 하지 않을까 싶습니다. 
어떻게 생각하시는지 궁금합니다..!

## 📝 To Do List
- [x]  회차 삭제 정보 반영 검토

**Comment by Arkady1356** [comment]
전에 말씀드린것 처럼
'에브리 타임', '블라인드'에서는 refresh를 하지 않습니다!

저는 refresh를 하는 것도 안하는 것도 둘 다 맞는 말이라고 생각합니다!
규현님은 refresh를 원하시는 것 같으니 방법을 찾아보도록 하겠습니다 ~

**Comment by rbgus2002** [comment]
직접 글을 작성한 뒤에 삭제해보면 아시겠지만 말씀하신 앱 모두 refresh를 해주고 있습니다..! 
refresh를 하는 것이 맞을 거 같습니다! 

더불어서 '에브리타임' 앱에서 자유게시판 목록을 들어가신 뒤에 뒤로가기를 통해 에브리타임 홈 화면을 가시면 refresh를 해주고 있습니다 ㅎㅎ
이 경우와 마찬가지로 저희 앱에서도 뒤로가기를 하면 refresh를 매번 해주는 것이 더 자연스러울 거 같습니다!

**Comment by Arkady1356** [comment]
엄...
"홈 화면 refresh"와 "리스트 형태의 화면의 refresh"는 약간의 차이가 존재합니다
홈 화면의 경우에는 기본적인 틀이 고정되어 있고, 내용물만 교체하면 되기 때문에 쉽게 refresh 할 수 있지만,
게시물 리스트 혹은 라운드 리스트와 같은 형태에서는 마지막에 보고 있던 스크롤 위치와 같이 고려해야할 요소가 훨씬 더 많아집니다.
(예를 들어 15번째 게시물 보고 나왔는데 리프레쉬되면서 3개의 게시물이 추가된다면? + 페이징까지 적용해야 된다면? => 머리 터짐)

이러한 이유에서인지 위에서 말씀드린 '에타', '블라인드'에서
게시판 -> 게시물 조회 -> 뒤로가기 하여도 refresh 되지 않습니다! (비록 홈화면은 refresh 되더라도)

하지만 ~ 언제든 그렇듯 해답을 찾을 수 있을거라 믿기에
함 도전해보고 정안된다 싶으면 다시 말슴 드리겟습니다 하하 ~

**Comment by rbgus2002** [comment]
> 엄... "홈 화면 refresh"와 "리스트 형태의 화면의 refresh"는 약간의 차이가 존재합니다 홈 화면의 경우에는 기본적인 틀이 고정되어 있고, 내용물만 교체하면 되기 때문에 쉽게 refresh 할 수 있지만, 게시물 리스트 혹은 라운드 리스트와 같은 형태에서는 마지막에 보고 있던 스크롤 위치와 같이 고려해야할 요소가 훨씬 더 많아집니다. (예를 들어 15번째 게시물 보고 나왔는데 리프레쉬되면서 3개의 게시물이 추가된다면? + 페이징까지 적용해야 된다면? => 머리 터짐)
> 
> 이러한 이유에서인지 위에서 말씀드린 '에타', '블라인드'에서 게시판 -> 게시물 조회 -> 뒤로가기 하여도 refresh 되지 않습니다! (비록 홈화면은 refresh 되더라도)
> 
> 하지만 ~ 언제나 그렇듯 해답을 찾을 수 있을거라 믿기에 함 도전해보고 정안된다 싶으면 다시 말슴 드리겟습니다 하하 ~

앗 그렇게 복잡한 경우면은 홈화면을 제외하고 리스트 형태의 화면은 refresh를 안해주셔도 될 거 같습니다!
그러면 당장은 홈화면의 경우에 refresh가 필요할 거 같고, 게시글 삭제 후에 목록 페이지로 redirect 되는 경우에 refresh가 필요할 거 같습니다!

**Comment by Arkady1356** [comment]
ㅋㅋㅋ 배려 감사합니다
그 뭐냐 회차 삭제시 리프레시는 아니더라도 삭제 애니메이션을 적용할 수는 있을 것 같습니다.
다른 부분 완성하고 이런 부분 찾아서 다 하도록 하겠습니다 !! !!!! !!!!!!!

**Comment by rbgus2002** [comment]
> ㅋㅋㅋ 배려 감사합니다 그 뭐냐 회차 삭제시 리프레시는 아니더라도 삭제 애니메이션을 적용할 수는 있을 것 같습니다. 다른 부분 완성하고 이런 부분 찾아서 다 하도록 하겠습니다 !! !!!! !!!!!!!

아하 네네넵 감사합니다~!~!~!~!~!!~
